template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '.github/**']

  - labels: ['C: source']
    patterns: ['**/*.py|-tests']

  - labels: ['C: docs']
    patterns: ['**/*.md|docs/**|messages/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: panels']
    patterns: ['panels/**']

  - labels: ['C: colors']
    patterns: ['lib/@(csscolors|rgba).py']

  - labels: ['C: ase']
    patterns: ['lib/ase.py']

  - labels: ['C: insert']
    patterns: ['color_helper_insert.py']

  - labels: ['C: picker']
    patterns: ['color_helper_picker.py']

  - labels: ['C: main']
    patterns: ['color_helper.py']

  - labels: ['C: palettes']
    patterns: ['*.palettes']

  - labels: ['C: settings']
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

# Label management

labels:
- name: 'C: panels'
  color: subcategory
  description: Related to panel templates.

- name: 'C: colors'
  color: subcategory
  description: Related to color handling.

- name: 'C: ase'
  color: subcategory
  description: Related to ASE.

- name: 'C: insert'
  color: subcategory
  description: Related to color insertion.

- name: 'C: picker'
  color: subcategory
  description: Related to the color picker.

- name: 'C: main'
  color: subcategory
  description: Main code.

- name: 'C: palettes'
  color: subcategory
  description: Palettes.

- name: 'C: settings'
  color: subcategory
  description: Sublime settins files.
